replace "First name" and "Surname" input fields with a single "Full Name" field
codu-code/codu pull request #1084
Opened 2024-10-07 16:06 UTC by sahilpatel2712

# ✨ Codu Pull Request 💻

Fixes issue #1080 

## Pull Request details

- replace "First name" and "Surname" input fields with a single "Full Name" field
- add Zod validation for the "Full Name" input field.

## Any Breaking changes

'None'

## Associated Screenshots
![Screenshot 2024-10-07 210429](https://github.com/user-attachments/assets/06440584-92e3-4fd8-bf57-b5f4f47783e9)

2024-10-07 18:29 UTC, John-Paul-Larkin requested changes
Looks great @sahilpatel2712 
One last thing. Could you please drop the firstName and surname columns from the database schema since we’re using fullname instead. You can modify the migration accordingly.
Thanks

2024-10-07 18:35 UTC, John-Paul-Larkin commented on app/(app)/alpha/additional-details/page.tsx
> +      name: true,
This can be safely ignored, since this alpha/settings page is legacy and will be deleted.

2024-10-07 19:34 UTC, sahilpatel2712 commented
sure...

2024-10-08 12:11 UTC, John-Paul-Larkin submitted a review, later dismissed
Great work, thanks @sahilpatel2712

2024-10-08 13:54 UTC, sahilpatel2712 commented
> Great work, thanks @sahilpatel2712

You're welcome!

2024-10-08 18:28 UTC, NiallJoeMaher commented
Just some prettier issues. Run `npm run prettier:fix` and it should solve it! Great work.

2024-10-09 05:48 UTC, sahilpatel2712 commented
> Just some prettier issues. Run `npm run prettier:fix` and it should solve it! Great work.

done..

2024-10-09 07:15 UTC, NiallJoeMaher approved these changes
🌮 🦖

2024-10-09 07:16 UTC, merged