Fixes Refetch of SideBar Posts on Bookmarked
codu-code/codu pull request #1112
Opened 2024-10-12 18:22 UTC by revanthnetha

# ✨ Codu Pull Request 💻

Fixes #834

Approach:
- So whenever in article something is bookmarked or unbookmarked, refetch of the myBookmarks i.e.SidePosts would happen.
- In order to do this, when mutate post in Article Preview is successfull, I have called the myBookmarks Query, So  the recent data shown in SideBarPosts.
- **Refetch Syncs Data**: When refetch() is called in Component 1 (e.g., after a bookmark mutation), Component 2 will also display the most recent data because React Query syncs the cache automatically across components.

Todo :
-  Instead of slicing the SidePosts in FE. I have modified the Trpc Query to take the limit and render the limit bookmarks SidePosts.
- we can also do in way by making two queries one for fetching the bookmarks until the limit and other for total Count. But I have found making oneQuery to fetch all bookmarks and then slicing is optimized as this query : ctx.db.query.bookmark.count(..) is not supporting.

Happy to do changes if needed :)

## Any Breaking changes
- None

## Associated Screenshots
- None

2024-10-13 10:33 UTC, John-Paul-Larkin commented on components/SideBar/SideBarSavedPosts.tsx
> +    limit: 3,
Instead of the magic number 3 for the limit, you should use the howManySavedToShow const

2024-10-13 10:35 UTC, John-Paul-Larkin commented
Hey @revanthnetha 
This works great, thanks.
I just left a small comment, but otherwise this is good to go 👍

2024-10-13 13:54 UTC, John-Paul-Larkin requested changes

2024-10-13 13:54 UTC, John-Paul-Larkin commented on components/SideBar/SideBarSavedPosts.tsx
> +  const { status: bookmarkStatus } = api.post.myBookmarks.useQuery({});
Can you please combine this query with the other one. This means we are making 2 queries when only one is necessary.

2024-10-13 13:56 UTC, revanthnetha commented
Got it @John-Paul-Larkin . I'll make the changes as necessary.

2024-10-14 09:23 UTC, revanthnetha commented
Review the changes @John-Paul-Larkin . Happy to do if any changes needed :)


Could you please add the labels hacktober-fest and hactober-fest-accepted tags and add my name in assigness. It really means a lot.

2024-10-14 15:19 UTC, John-Paul-Larkin commented
Hey @revanthnetha 
This is great work. Thanks. 
I was playing with this earlier and I received the error Toast, but I dont know why that happened and try as I may I cant seem to recreate it. 

@NiallJoeMaher Do you think we remove the toast on error?
Apart from that, I think this is ready to go.

2024-10-14 15:20 UTC, John-Paul-Larkin approved these changes

2024-10-14 18:01 UTC, merged