Test/years of experience
codu-code/codu pull request #1121
Opened 2024-10-14 15:29 UTC by leslyclopez11

# ✨ Codu Pull Request 💻

Fixes #1009

## Pull Request details

- I added code to _client.tsx modifying slideThree (including the dropdown)
- Defined yearsOfExperience in additionalUserDetails.tsx
- Defined yearsOfExperience in page.tsx
- Defined yearsOfExperience in schema.ts
- I added validation based on coderabbitai suggestions
- Attempted to create the Drizzle migration
- I cherry-picked from the develop branch the commits, but I'm confused if I'm doing this right.

## Any Breaking changes

- 'None'

## Associated Screenshots

- 'None'

2024-10-14 15:49 UTC, John-Paul-Larkin commented
Hey @leslyclopez11 
Great to see you back! I am sure you learned loads about Git 🤣 
I see you have two PRs open now. 
Test/years of experience #1121 and Feature/years of experience #1120

Which one of these can be closed?

2024-10-14 16:04 UTC, leslyclopez11 commented
@John-Paul-Larkin oh, I fear I did learn a lot of git. Hopefully, I did the PR correct now but let me know if that's not the case. I feel more confident with this one: Test/years of experience https://github.com/codu-code/codu/pull/1121

2024-10-14 16:13 UTC, John-Paul-Larkin commented
> @John-Paul-Larkin oh, I fear I did learn a lot of git. Hopefully, I did the PR correct now but let me know if that's not the case. I feel more confident with this one: Test/years of experience #1121

Great, so I will close the other PR and review this one. 
PS. Git is complicated and very powerful, but it will all start to make sense to you soon!

2024-10-15 17:05 UTC, John-Paul-Larkin commented
Hey @leslyclopez11 
This is great work. Thanks very much.
You are nearly there with this PR, but there are a few small things we should fix first.

The value '0-1' is defaulted to for every record. 
The database is not actually being update with the entered value. 
You can search for the function "slideThreeSubmitAction", which is in the _actions file in the additional-details directory.
This is a Next.js server and is invoked to update the database. 
You can follow the pattern to update the database with the yearsOfExperience value.

On the same thing we actually dont want a default value for this. The filed should be null until the user inputs something in the form.

If you run "npx drizzle-kit studio" it will connect to your database and spin up proxy server for Drizzle Studio which you can use for viewing the database.

I hope this all makes sense?

2024-10-19 07:09 UTC, NiallJoeMaher commented
Is this still being worked on? Just so I know if I should keep it open or close?

2024-10-19 10:45 UTC, leslyclopez11 commented
@NiallJoeMaher I'm still working on this!

2024-10-28 10:41 UTC, NiallJoeMaher requested changes

2024-10-28 10:41 UTC, NiallJoeMaher commented on drizzle/0010_gorgeous_living_tribunal.sql
There should be only one migration file for the updates. Let me know if you still want to take this on or else we can take it over.

2024-10-28 19:55 UTC, closed without merging