Fix fancy link - issue #1160
codu-code/codu pull request #1164
Opened 2024-10-21 10:06 UTC by amankumarconnect

# ✨ Codu Pull Request 💻

Fixes #1160 

## Pull Request details

- Removed the .fancy-link and .fancy-link:hover classes from globals.css as part of the effort to follow the component-based styling approach promoted by Tailwind CSS.
- Applied the styles directly to the components using .fancy-link, replacing them with the equivalent Tailwind classes:
cursor-pointer bg-gradient-to-r from-orange-400 to-pink-600 bg-clip-text tracking-wide text-transparent hover:from-orange-300 hover:to-pink-500
- Ensured that the hover effects and link styling remain consistent across all relevant components.

## Any Breaking changes

None

## Associated Screenshots

None

2024-10-21 14:38 UTC, John-Paul-Larkin approved these changes

2024-10-21 14:42 UTC, John-Paul-Larkin requested changes
Hey @amankumarconnect 
Can you please run the prettier script, and commit the changes. Thanks.
npm run prettier:fix

2024-10-21 15:27 UTC, amankumarconnect commented
@John-Paul-Larkin  I ran the script and committed the changes.
Kindly have a look

2024-10-22 12:34 UTC, NiallJoeMaher commented
Closing this as the author wasn't assigned the issue.

2024-10-22 12:34 UTC, closed without merging

2024-10-22 13:14 UTC, amankumarhq commented
My apologies, @NiallJoeMaher. I wasn’t aware that working on an already assigned issue wasn’t allowed. I mistakenly thought that the assignment would be given to whoever opened a PR first. Thank you for pointing that out!

2024-10-22 18:22 UTC, amankumarconnect commented
@NiallJoeMaher 
Also, could you kindly add this information to the [CONTRIBUTING.md](https://github.com/codu-code/codu/blob/develop/CONTRIBUTING.md) to help prevent others from being labeled as **"SPAM"** _for opening a PR without having the issue assigned_? Thank you!

2024-10-22 20:30 UTC, NiallJoeMaher commented
@amankumarconnect I removed the spam label since it seems like an honest mistake. It's general knowledge in Open Source that you need to be assigned an issue to work on it to stop multiple people working on/rushing or racing to finish issues. Feel free to comment on another unassigned issue if you want to tackle it.