Fix footer not sticky on the bottom
codu-code/codu pull request #1173
Opened 2024-10-24 16:53 UTC by lindotex

`#` ✨ Codu Pull Request 💻

Fixes #1171 

## Pull Request details
- Added an min height to the post component. (tiny small change), because I didn't want to make any huge alterations on the code.

## Any Breaking changes

- None

## Associated Screenshots

Desktop:
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/e28397ca-348b-495d-adb7-ea123f73bf94">

Mobile:
<img width="375" alt="image" src="https://github.com/user-attachments/assets/98d8fcc3-dfcb-4ab1-92f7-a08c6705131c">

2024-10-24 18:16 UTC, NiallJoeMaher requested changes
The env should not be deleted and the min-h-96 might be too high or low depending on the screen size.

2024-10-26 22:39 UTC, NiallJoeMaher commented
Just need `npm run prettier:fix`

2024-10-28 11:17 UTC, NiallJoeMaher requested changes

2024-10-28 11:17 UTC, NiallJoeMaher commented on app/(app)/layout.tsx
>      <>
No longer need the fragments. Let me know if you have time to update this.

2024-10-28 19:57 UTC, NiallJoeMaher commented
You can reopen if you decide to tackle again.

2024-10-28 19:57 UTC, closed without merging

2024-10-29 07:10 UTC, lindotex commented
Sorry by my late answer.
I was Traveling 😅...
I have the code ready.

2024-11-03 10:08 UTC, Zaid-B24 commented
I can work on this issue, if no one has any problem with it.