updated layout
codu-code/codu pull request #1212
Opened 2024-11-07 09:26 UTC by Zaid-B24

# ✨ Codu Pull Request 💻

Fixes #(1171)

## Pull Request details

- Fixed Fotter not sticking to bottom in Your posts section
- Removed fragments in Layout file
- Added a main wrapper around children in layout file to center content

## Any Breaking changes

- None

## Associated Screenshots

![footer](https://github.com/user-attachments/assets/44d2b408-edab-4ce7-bba0-7aade301e383)

## [Optional] What gif best describes this PR or how it makes you feel

-  None

2024-11-11 21:01 UTC, CarolinaCobo commented
hey @Zaid-B24 it seems some of the tests are failing, would you mind fixing them?

2024-11-11 21:10 UTC, CarolinaCobo requested changes

2024-11-11 21:10 UTC, CarolinaCobo commented on app/(app)/layout.tsx
> +    <div className="grid min-h-screen grid-rows-[auto_1fr_auto]">
could you try a different approach instead of the `grid-rows-[auto_1fr_auto]`? Maybe using flex-col instead of grid. Thanks!

2024-11-12 08:36 UTC, Zaid-B24 commented
@CarolinaCobo I used flex flex-col min-h-screen, to stick the footer to bottom, can you please review it .?

2024-11-12 18:59 UTC, CarolinaCobo commented
@Zaid-B24 looks good!  There are some prettier errors now, could you run `prettier:fix`? thanks

2024-11-16 12:09 UTC, NiallJoeMaher requested changes
These changes need to be tested everywhere. When testing myself I noticed that the layout no breaks other places. Eg the article feed:
![Distorted homepage view](https://github.com/user-attachments/assets/712613c6-6651-4ac5-89c1-bd6d04e91ef5)

2024-11-17 06:27 UTC, Zaid-B24 commented
ok, I will test the changes everywhere.

2025-02-09 14:31 UTC, CarolinaCobo commented
Stale

2025-02-09 14:31 UTC, closed without merging