Feature/complete onboarding form
codu-code/codu pull request #1216
Opened 2024-11-12 19:17 UTC by John-Paul-Larkin

# ✨ Codu Pull Request 💻

Fixes #(issue)

## Pull Request details

- This PR completes the onboarding form

- Add a ‘years of experience’ select question when the user selects ‘Working professional’
- Create migration to add two fields to the user table
    yearsOfExperience text field and onboardingComplete timestamp field

- Adds a check for completion and redirect on Login
- Perform isOnboardingComplete database check in the session callback 
- Add isOnboardingComplete boolean to the session for onboarding status tracking.
- Add component within AuthProvider to verify if the user has completed onboarding and redirect if not.

## Attempts to handle the onboarding redirect - Open to suggestions
- Middleware: Attempted to use middleware, but it can’t access the session or database.
- JWT Strategy: Tried adding an isOnboardingComplete field to the JWT, but strategy: "jwt" doesn’t integrate well with our session setup.
- Root Layout Check: Added a server-side check in the RootLayout, but this led to repeated redirects.

- In the end I added the check client side to the AuthProvider. Not ideal, but it works.  

## Any Breaking changes

- I altered the E2E setup.ts to prevent breaking tests.

## [Optional] What gif best describes this PR or how it makes you feel
![SpongeBob](
https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExeW15eHY2eGdyZ2R0cjJ1ZjFhODJ3NWFwc2JkMmtqamRjN3lweGhoZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7aCTPPm4OHfRLSH6/giphy.gif)

2024-11-16 11:52 UTC, NiallJoeMaher requested changes

2024-11-16 11:52 UTC, NiallJoeMaher commented on context/AuthProvider.tsx
> +  console.log("-------------");
Log

2024-11-16 11:52 UTC, NiallJoeMaher commented on server/db/schema.ts
> +    yearsOfExperience: text("yearsOfExperience"),
We should probably use ENUMs here. 
```
CREATE TYPE experience_range AS ENUM ('0-1', '1-3', '3-5', '5-8', '12+');
```

2025-02-12 20:26 UTC, CarolinaCobo commented on context/AuthProvider.tsx
> +  console.log("-------------");
@John-Paul-Larkin will you remove this log and address the coderabbitai comments too so I can merge? :)

2026-06-14 20:54 UTC, closed without merging