showing articles in chronological order
codu-code/codu pull request #40
Opened 2022-08-08 12:12 UTC by 0xPranjl

2022-08-08 16:29 UTC, NiallJoeMaher requested changes
This should be done in the `getAllArticlesMetadata` function so that it happens before the page is loaded. It would just make it a little more optimal. 

Thanks for contributing too! Great to have you here ❤️

2022-08-09 06:33 UTC, pkspyder007 commented
@0xPranjl As Niall said we can move this to server side logic in the `getAllArticlesMetadata` by just sorting on date in frontmatter at the time of returning.

```js
return metadata.sort((a, b) => {
     return (new Date(b.date).valueOf() - new Date(a.date).valueOf());
});
```

2022-08-09 07:05 UTC, 0xPranjl commented
thanks @pkspyder007 I have applied this logic

2022-08-09 13:10 UTC, NiallJoeMaher commented on pages/articles/index.tsx
> +import { Temporal } from "@js-temporal/polyfill";
Are these imports needed now?

2022-08-09 13:14 UTC, NiallJoeMaher approved these changes

2022-08-09 13:16 UTC, merged

2022-08-09 13:18 UTC, NiallJoeMaher commented
@0xPranjl your changes are live! Nice one. https://codu.co/articles

2022-08-09 13:23 UTC, 0xPranjl commented
thanks

2022-08-09 15:25 UTC, pkspyder007 commented
Congrats @0xPranjl on your first pr merge 🥳

2022-08-09 15:28 UTC, 0xPranjl commented
thanks @pkspyder007