Debounce
codu-code/codu pull request #495
Opened 2023-10-07 04:10 UTC by s0ham075

# ✨ Codu Pull Request 💻

![Codu Logo](https://raw.githubusercontent.com/codu-code/codu/develop/public/images/codu-gradient.png)

## Pull Request details:
- debounced  article page search bar using useDebounce hook

## Any Breaking changes:
- None

## Associated Screenshots:
- None

2023-10-07 08:38 UTC, NiallJoeMaher requested changes
A few things to remove but looks good! 🦾

2023-10-07 08:38 UTC, NiallJoeMaher commented on .swc/plugins/v7_linux_x86_64_0.102.1/d560cf24a4aa929c89b44fd051c5acffb1acc62347383cb9e2fbb7eb927f8f7b
Don't commit the binary, please. This is from a previous commit that I had to remove. But it should have been stopped by the `.gitignore`.

2023-10-07 08:38 UTC, NiallJoeMaher commented on next.config.js
> +    // For all available options, see:
Seems to be an older commit you are working off because these commits aren't needed.

2023-10-07 08:38 UTC, NiallJoeMaher commented on .gitignore
> +# CDK asset staging directory
Not sure what happened here since it looks like duplicated everything in this addition to the `gitignore`

2023-10-08 03:48 UTC, s0ham075 commented on .swc/plugins/v7_linux_x86_64_0.102.1/d560cf24a4aa929c89b44fd051c5acffb1acc62347383cb9e2fbb7eb927f8f7b
I don't understand, is this a file which needs to be removed?

2023-10-10 17:37 UTC, NiallJoeMaher commented on .swc/plugins/v7_linux_x86_64_0.102.1/d560cf24a4aa929c89b44fd051c5acffb1acc62347383cb9e2fbb7eb927f8f7b
Yes, it's not needed. I think something is wrong with your git history so maybe you could try closing this PR and opening with a clean branch?

2023-10-11 20:09 UTC, NiallJoeMaher commented
Closing since it seems to be stale. Feel free to reopen if it becomes active again or you have fixes 🦾 

Thanks for the help. 😄

2023-10-11 20:09 UTC, closed without merging