fix:#549
codu-code/codu pull request #563
Opened 2023-10-19 17:48 UTC by RajuGangitla

# ✨ Codu Pull Request 💻

## Pull Request details:
- Changed the "Heading 1" to "Heading" and "Heading 2" to "Subheading" and changed icons to Heading from Lucide 

## Associated Screenshots:

    
![🚨 WIP - Things will break - Google Chrome 19-10-2023 23_14_00](https://github.com/codu-code/codu/assets/113505439/f0a1da2d-5bb0-4aa3-869f-6184a7b0f092)

2023-10-19 18:40 UTC, NiallJoeMaher requested changes

2023-10-19 18:40 UTC, NiallJoeMaher commented on package-lock.json
Could you remove this file please? These changes shouldn't have changed the lock file. Everything else is great so once it's removed I'll get it merged. 🦾

2023-10-19 19:15 UTC, NiallJoeMaher commented on package-lock.json
I think I mistook my words. I mean unstage the file (as in there should have been no changes to that file).

2023-10-19 22:17 UTC, NiallJoeMaher commented on package-lock.json
I think you unstaged the wrong files 🙈 If you can revert I'll get this merged.

2023-10-20 06:49 UTC, NiallJoeMaher commented
Let me know if you need help! 🤔 

![Screenshot 2023-10-20 at 07 48 55](https://github.com/codu-code/codu/assets/12615742/8bda59e6-2ed7-4adb-8618-7b1e60cf34be)

2023-10-20 07:04 UTC, RajuGangitla commented
i merge the latest code into my forked code and did the changes again now changed the code only in bubble menu

2023-10-20 07:53 UTC, NiallJoeMaher requested changes

2023-10-20 07:53 UTC, NiallJoeMaher commented on components/editor/editor/components/node-selector.tsx
> +      name: "SubHeading",
Small typo and then I'll get it merged. Should be`Subheading` not `SubHeading`.

2023-10-20 08:23 UTC, NiallJoeMaher approved these changes
LGTM! 🌮 Well done. 🚀

2023-10-20 08:25 UTC, RajuGangitla commented
Thank you @NiallJoeMaher I made my first open source contribution. I'm looking forward to contribute more

2023-10-20 08:25 UTC, merged