Schedule post
codu-code/codu pull request #704
Opened 2024-01-30 20:02 UTC by thanhsonng

# ✨ Codu Pull Request 💻

![Codu Logo](https://raw.githubusercontent.com/codu-code/codu/develop/public/images/codu-gradient.png)

## Pull Request details

✅  Close #689 and #702 
    - Implement post scheduling feature using the field `published` of the table `Post` (see discussion in #689).
    - `/articles` page now only includes posts that are considered published according to the new logic.
    - `/create` page now supports post scheduling (see screenshots).
    - `/my-posts` page now includes an additional tab `Scheduled`. Additionally, published time and scheduled time are also added in respective tabs (see screenshots).
🐞  Fix some existing bugs on `/create` page.
    - Fix incorrect id for tag input.
    - Fix redirection after submitting form (use `router.push` because `redirect` doesn't work with client component).
    - Fix toast when post fails to submit.
    - Improve some button label text.

## Any Breaking changes

New feature, some stuff was renamed. Shouldn't break anything, but some alpha components should be updated later to include this new feature (`/app/alpha/new/[[...postIdArr]]/_client.tsx` for example).

## Associated Screenshots

<img width="1370" alt="image" src="https://github.com/codu-code/codu/assets/28614996/1796168c-2ff4-4568-ad40-63d9f85d3278">
<hr>
<img width="1370" alt="image" src="https://github.com/codu-code/codu/assets/28614996/c5fd4b44-c21b-46f0-a6c0-2d7d42de9027">
<hr>
<img width="1367" alt="image" src="https://github.com/codu-code/codu/assets/28614996/6475e936-3672-44f1-a944-98ddc567a936">
Using browser's native date time picker. A scheduled post can be re-scheduled as long as it has not hit published time yet.
<hr>
<img width="1370" alt="image" src="https://github.com/codu-code/codu/assets/28614996/2eb98ee4-ea59-44b3-b039-fee917aa071a">
Scheduled posts are sorted by ascending schedule (published) time.
<hr>
<img width="1370" alt="image" src="https://github.com/codu-code/codu/assets/28614996/66092c34-c2d3-4b5f-acf8-dbeb287034e3">
Published time is added to the bottom of the card. Sorting order doesn't change.

2024-01-30 20:03 UTC, thanhsonng commented on utils/post.ts
@NiallJoeMaher I am not sure if creating a new file is appropriate for this helper utility. Let me know if this needs changing.

2024-01-30 20:05 UTC, thanhsonng commented on components/Switch/Switch.tsx
Creating a new UI component. I think we may need a design system soon.

2024-01-30 20:08 UTC, NiallJoeMaher commented on components/Switch/Switch.tsx
Do you think it would be better without a toggle? Maybe like if it's populated or not? With a clear button?

Another question, does this make sure we can't post something in the past?

I'm reviewing on my phone so I could be missing it. 😅

2024-01-30 20:17 UTC, thanhsonng commented on components/Switch/Switch.tsx
@NiallJoeMaher 

You are right, I forgot to handle that case. Will push some more code soon.

We could do it without a toggle for sure. I'm just coming up with a proposal for the UI here, and actually the toggle was inspired by TikTok. 

In my opinion, having a toggle could be clearer than having an empty/populated input, but since you will likely use this feature much more than me, I'm open to your input.

2024-01-30 23:34 UTC, thanhsonng commented on components/Switch/Switch.tsx
Added a commit to handle past schedule time

2024-01-31 20:20 UTC, NiallJoeMaher requested changes
One last thing I think 🤔 But I think the `[username]` will need to be updated too!

2024-01-31 22:18 UTC, thanhsonng commented
> One last thing I think 🤔 But I think the `[username]` will need to be updated too!

@NiallJoeMaher Can you be more specific? I don't get what you are referring to, because AFAIK this PR doesn't change anything related to username.

Also, I know this is a large PR, so no pressure to merge quickly, boss.

2024-02-01 13:04 UTC, NiallJoeMaher commented
> > One last thing I think 🤔 But I think the `[username]` will need to be updated too!
> 
> @NiallJoeMaher Can you be more specific? I don't get what you are referring to, because AFAIK this PR doesn't change anything related to username.
> 
> Also, I know this is a large PR, so no pressure to merge quickly, boss.

For example, if I got to https://www.codu.co/niall I see all of my articles. Every user has all of their own posts on their page.

2024-02-02 20:47 UTC, NiallJoeMaher commented
@thanhsonng let me know if the last comment makes sense. 🦾 Thanks!

2024-02-02 23:03 UTC, thanhsonng commented
> @thanhsonng let me know if the last comment makes sense. 🦾 Thanks! 

@NiallJoeMaher yes it does, thanks for the example it really cleared things up. I will add a couple more commits soon.

2024-02-03 00:29 UTC, thanhsonng commented
@NiallJoeMaher Updated, thanks for catching it, I totally missed that [username] page. That's why code reviews are awesome 😎 If I miss anything else just let me know.

2024-02-03 12:07 UTC, NiallJoeMaher approved these changes
LGTM! Nice one 🦾

2024-02-03 12:07 UTC, merged